// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-test/event"
)

// Injectors from wire.go:

func InitEvent(msg string) (event.Event, error) {
	message := event.NewMessage(msg)
	greeter := event.NewGreeter(message)
	eventEvent, err := event.NewEvent(greeter)
	if err != nil {
		return event.Event{}, err
	}
	return eventEvent, nil
}
